### ISSUE TITLE
关于连续对话的问题 This model's maximum context length is 4097 tokens. However, you requested xxx tokens

### ISSUE THREAD

**Issue by FlickerMi** [Grt1228/chatgpt-java#104]
非常感谢这个开源项目，关于连续对话这个问题一直没想通，想请教一下大家。

使用chatCompletions方法，老是会报错This model's maximum context length is 4097 tokens. However, you requested xxx tokens

但是我发送到API的内容，其实内容很少，为什么会报这个错呢？

我尝试调用了一下官方接口 /v1/chat/completions ，请求体如下：

```
{
    "model": "gpt-3.5-turbo",
    "messages": [
        {
            "role": "user",
            "content": "继续"
        },
        {
            "role": "assistant",
            "content": "请问您需要什么帮助？"
        },
        {
            "role": "user",
            "content": "从现在开始你叫siri"
        },
        {
            "role": "user",
            "content": "继续"
        },
        {
            "role": "user",
            "content": "你好"
        }
    ],
    "temperature": 0.2,
    "n": 1,
    "stream": true,
    "top_p": 1.0,
    "max_tokens": 4096,
    "presence_penalty": 0.0,
    "frequency_penalty": 0.0
}
```

就会报错：This model's maximum context length is 4097 tokens. However, you requested 4155 tokens (59 in the messages, 4096 in the completion). Please reduce the length of the messages or completion.",

不设置max_tokens不会报错，设置为4096反而就会报错。

我理解的max_tokens是api回复的最大token数。所以这个报错的计算token数方法是（max_tokens + api传入的token）不能大于4096？

那连续对话的最佳实践应该是如何呢？如果我设置的max_tokens是2048，那么传入API的token数就不能大于2048了，传入前计算如果大于2048，就截取掉最前面的内容？希望能解答给出一些思路。谢谢

**Comment by Grt1228** [comment]
我理解的max_tokens是api回复的最大token数。所以这个报错的计算token数方法是（max_tokens + api传入的token）不能大于4096？  **是这样的**

更新1.0.11 通过计算token的方式，动态传入max_token

**Comment by Grt1228** [comment]
> 非常感谢这个开源项目，关于连续对话这个问题一直没想通，想请教一下大家。
> 
> 使用chatCompletions方法，老是会报错This model's maximum context length is 4097 tokens. However, you requested xxx tokens
> 
> 但是我发送到API的内容，其实内容很少，为什么会报这个错呢？
> 
> 我尝试调用了一下官方接口 /v1/chat/completions ，请求体如下：
> 
> ```
> {
>     "model": "gpt-3.5-turbo",
>     "messages": [
>         {
>             "role": "user",
>             "content": "继续"
>         },
>         {
>             "role": "assistant",
>             "content": "请问您需要什么帮助？"
>         },
>         {
>             "role": "user",
>             "content": "从现在开始你叫siri"
>         },
>         {
>             "role": "user",
>             "content": "继续"
>         },
>         {
>             "role": "user",
>             "content": "你好"
>         }
>     ],
>     "temperature": 0.2,
>     "n": 1,
>     "stream": true,
>     "top_p": 1.0,
>     "max_tokens": 4096,
>     "presence_penalty": 0.0,
>     "frequency_penalty": 0.0
> }
> ```
> 
> 就会报错：This model's maximum context length is 4097 tokens. However, you requested 4155 tokens (59 in the messages, 4096 in the completion). Please reduce the length of the messages or completion.",
> 
> 不设置max_tokens不会报错，设置为4096反而就会报错。
> 
> 我理解的max_tokens是api回复的最大token数。所以这个报错的计算token数方法是（max_tokens + api传入的token）不能大于4096？
> 
> 那连续对话的最佳实践应该是如何呢？如果我设置的max_tokens是2048，那么传入API的token数就不能大于2048了，传入前计算如果大于2048，就截取掉最前面的内容？希望能解答给出一些思路。谢谢

@FlickerMi
