### ISSUE TITLE
cn.hutool.json.JSONException: Mismatched head and title at 396

### ISSUE THREAD

**Issue by scit1977** [Grt1228/chatgpt-java#108]
使用参考的completionsV3()报错
17:07:59.036 [http-nio-8080-exec-1] INFO  c.u.c.i.OpenAILogger - [log,16] - OkHttp-------->:--> POST https://chatai.1rmb.tk/api/v1/completions
17:07:59.036 [http-nio-8080-exec-1] INFO  c.u.c.i.OpenAILogger - [log,16] - OkHttp-------->:Content-Type: application/json; charset=UTF-8
17:07:59.036 [http-nio-8080-exec-1] INFO  c.u.c.i.OpenAILogger - [log,16] - OkHttp-------->:Content-Length: 273
17:07:59.036 [http-nio-8080-exec-1] INFO  c.u.c.i.OpenAILogger - [log,16] - OkHttp-------->:
17:07:59.036 [http-nio-8080-exec-1] INFO  c.u.c.i.OpenAILogger - [log,16] - OkHttp-------->:{"model":"text-davinci-003","prompt":"Human: 帮我把下面的文本翻译成英文；我爱你中国\n","temperature":0.0,"n":1,"stream":false,"echo":true,"stop":[" Human:"," Bot:"],"max_tokens":2048,"top_p":1.0,"presence_penalty":0.0,"frequency_penalty":0.0,"best_of":1}
17:07:59.037 [http-nio-8080-exec-1] INFO  c.u.c.i.OpenAILogger - [log,16] - OkHttp-------->:--> END POST (273-byte body)
17:08:00.353 [http-nio-8080-exec-1] INFO  c.u.c.i.OpenAILogger - [log,16] - OkHttp-------->:<-- HTTP FAILED: cn.hutool.json.JSONException: Mismatched head and title at 396 [character 74 line 11]
17:08:00.361 [http-nio-8080-exec-1] ERROR c.r.f.w.e.GlobalExceptionHandler - [handleRuntimeException,69] - 请求地址'/gpt/chat',发生未知异常.
cn.hutool.json.JSONException: Mismatched head and title at 396 [character 74 line 11]

**Comment by Grt1228** [comment]
@scit1977 你好可以加群或者微信  详细说贴下报错日志么？
