### ISSUE TITLE
Invalid request to GET /50x.html. You provided a body with this GET request. Either submit a POST request, or pass your arguments in the query string

### ISSUE THREAD

**Issue by xiongxiong-op** [Grt1228/chatgpt-java#109]
![image](https://user-images.githubusercontent.com/56429049/230924663-88b0f9b6-e0fd-4f4b-b6f9-5fddb9764441.png)

{
  "error": {
    "message": "Invalid request to GET /50x.html. You provided a body with this GET request. Either submit a POST request, or pass your arguments in the query string.",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }

**Comment by xiongxiong-op** [comment]
其他问题正常回答，下面这个问题就报异常了。

做个校园模拟游戏的策划，包括游戏的主要属性，玩家身份，建筑场景，游戏任务，要求用户有一定的复玩率，能在游戏中找到进阶的成就感

**Comment by liyunfei0302** [comment]
@xiongxiong-op 解决了吗？什么原因啊
