### ISSUE TITLE
TikTokensUtils

### ISSUE THREAD

**Issue by yangyearsYhq** [Grt1228/chatgpt-java#110]
在通过Message的方式计算tokens的时候，使用方法：com.unfbx.chatgpt.entity.chat.ChatCompletion#tokens
底层调用：com.unfbx.chatgpt.utils.TikTokensUtil#getEncoding(java.lang.String)的时候，每个Message都会registry一次：
        EncodingRegistry registry = Encodings.newDefaultEncodingRegistry();
这是为什么？？

**Comment by PlexPt** [comment]
https://github.com/Grt1228/chatgpt-java/issues/114

**Comment by Grt1228** [comment]
这个在1.0.11已经修改了吧
@yangyearsYhq

**Comment by Grt1228** [comment]
感谢支持 反馈，1.012已修复
