### ISSUE TITLE
speechToTextTranscriptions方法默认返回的是繁体中文

### ISSUE THREAD

**Issue by wufug** [Grt1228/chatgpt-java#111]
OpenAiApi的
@Multipart
@POST("v1/audio/transcriptions")
Single<WhisperResponse> speechToTextTranscriptions(@Part MultipartBody.Part file,   @Part("model") RequestBody model);
接口方法默认返回的是繁体中文，可以增加一个参数@PartMap() Map<String, RequestBody> requestBodyMap
这时在调用时：
 requestBodyMap.put("prompt", RequestBody.create(MediaType.parse("multipart/form-data"), "简体中文"));
 Single<WhisperResponse> whisperResponse = this.openAiApi.speechToTextTranscriptions(multipartBody, modelBody,requestBodyMap);
就可以返回简体中文了，希望在OpenAiApi中增加此方法

**Comment by Grt1228** [comment]
谢谢你的反馈   下版本支持
