### ISSUE TITLE
在客户端调用模型是GPT_3_5_TURBO 而openai api返回的用的是gpt-3.5-turbo-0301

### ISSUE THREAD

**Issue by jackyzyaq** [Grt1228/chatgpt-java#119]
**在客户端调用模型是GPT_3_5_TURBO 而openai api返回的用的是gpt-3.5-turbo-0301，不知是封装的代码里是否不支持指定还是openai官方要求的？**

接口调用是指定的模型：
![image](https://user-images.githubusercontent.com/26595866/233814741-4d6dd6e0-3362-4bb3-b32c-fddb7a5d24bb.png)

接口返回的：

<img width="1468" alt="image" src="https://user-images.githubusercontent.com/26595866/233814765-de30904a-37d9-4ce6-b23f-159c4ca6ccbe.png">

非常感谢！

**Comment by classfang** [comment]
同样是这个问题

**Comment by heshujing** [comment]
同样是这个问题
