### ISSUE TITLE
程序不停止运行

### ISSUE THREAD

**Issue by imlee2021** [Grt1228/chatgpt-java#120]
main方法都执行完之后，依然不停止。是okhttp的问题吗？

**Comment by imlee2021** [comment]
还有一个问题，配置多个key的时候，使用KeyRandomStrategy，是每次请求换一个还是，初始化之后就是固定的了？

**Comment by Grt1228** [comment]
> main方法都执行完之后，依然不停止。是okhttp的问题吗？

使用的项目中的Test么？，是流式输出测试类么？

**Comment by Grt1228** [comment]
> KeyRandomStrategy

每次请求随机选一个。可以自定义实现key的获取策略，实现KeyStrategyFunction接口就可以了

**Comment by AoungY** [comment]
直接使用项目中的demo,openai 关闭sse连接后，程序还是在跑怎么办qwq

**Comment by Grt1228** [comment]
> 直接使用项目中的demo,openai 关闭sse连接后，程序还是在跑怎么办qwq

是这样的。因为是流式输出，要保证所有的请求返回回来。所以加了CountDownLatch。
集成到web应用删掉就好了
