### ISSUE TITLE
请问有没有支持Azure OpenAI的计划？

### ISSUE THREAD

**Issue by 4rayl** [Grt1228/chatgpt-java#121]

**Comment by Grt1228** [comment]
有项目地址么？或者文档地址么？
@4rayl

**Comment by 4rayl** [comment]
感觉大部份参数都是一样的，端点和版本以及API-KEY的字段上有些区别

https://learn.microsoft.com/en-us/azure/cognitive-services/openai/reference

@Grt1228

**Comment by Grt1228** [comment]
可以自己拉源码修改下

**Comment by LuaIJ** [comment]
@Grt1228 可以实现支持下吗
