### ISSUE TITLE
请问怎么调整返回图片的尺寸？

### ISSUE THREAD

**Issue by scit1977** [Grt1228/chatgpt-java#124]
//获取图片
        ImageResponse imageResponse = openAiClient.genImages(prompt); 这里没办法设置图片尺寸
        
    /**
     * 根据描述生成图片
     *
     * @param prompt
     * @return ImageResponse
     */
    public ImageResponse genImages(String prompt) {
        Image image = Image.builder().prompt(prompt).build();
        return this.genImages(image);
    }
这个默认尺寸可以修改吗？
@Builder.Default
    private String size = SizeEnum.size_512.getName();

**Comment by Grt1228** [comment]
可以修改，Image.builder().prompt(prompt).size("写上尺寸就好了").build()

参考：SizeEnum
