### ISSUE TITLE
国内可直接访问ChatGPT体验站案例

### ISSUE THREAD

**Issue by zizhu8** [Grt1228/chatgpt-java#127]
项目名称：ChatGPT体验站
项目开源地址：商业项目，支持企业私有化部署
项目简介：https://juejin.cn/post/7214068367606349885
项目类型：个人
使用到的SDK：1.0.12版本，直接依赖chatgpt-java SDK
访问地址：[ChatGPT体验站](https://zizhu888.cn/chatgpt/index.html)
图片AI访问地址：[图片AI-文生图](https://zizhu888.cn/text2img/index.html)
虚拟商城+个人支付解决方案：https://zizhu888.cn/faka-shop

**Comment by Grt1228** [comment]
提交到https://github.com/Grt1228/chatgpt-java/issues/87
