### ISSUE TITLE
流式问答如何找出自己的提问和回答的对应关系？

### ISSUE THREAD

**Issue by zouhan6806504** [Grt1228/chatgpt-java#132]
我用sseEmitter.send(SseEmitter.event().id(sid + "").name("连接成功！！！！").data(LocalDateTime.now()).reconnectTime(3000));
其中sid是自定义请求id
返回信息的时候onEvent(EventSource eventSource, String id, String type, String data) 
这里的id是null
通过completionResponse.getId()得到的id又是chatgpt自己的id，和我的sid无关
如何建立sid和chatgpt自己的id的对应关系

**Comment by Grt1228** [comment]
请问你说的这个id对应是有什么场景需要呢？

**Comment by zouhan6806504** [comment]
> 请问你说的这个id对应是有什么场景需要呢？

需要记录chatgpt给用户返回的信息，现在虽然知道返回的内容，但是这些内容对应到哪个原始的请求不清楚

**Comment by Grt1228** [comment]
这个要自己记录到数据库的。具体业务实现可以自己实现
