### ISSUE TITLE
ChatCompletion 使用 stream 时，报错。不用 stream 就正常。

### ISSUE THREAD

**Issue by iszhouhuabo** [Grt1228/chatgpt-java#138]
<img width="1204" alt="image" src="https://github.com/Grt1228/chatgpt-java/assets/100272598/a8d63d1d-894e-47c8-8b12-0b2bcf0210f4">

错误信息：

Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'data': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 5]] with root cause
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'data': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 5]

**Comment by Grt1228** [comment]
使用stream时候使用OpenAiStreamClient

如果两个都用的话建议实例化两个Client，使用同一个OkHttpClient
