### ISSUE TITLE
ChatGPTTest无法使用

### ISSUE THREAD

**Issue by 1390056263** [Grt1228/chatgpt-java#14]
ChatGPTTest,替换apikey后执行报错。

**Comment by Grt1228** [comment]
可以贴下错误信息么？

ps：建议使用OpenAIClient方式调用

**Comment by java668** [comment]
{
  "error": {
    "message": "Unrecognized request arguments supplied: bestOf, frequencyPenalty, maxTokens, presencePenalty, topP",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}

**Comment by java668** [comment]
错误信息
{
  "error": {
    "message": "Unrecognized request arguments supplied: bestOf, frequencyPenalty, maxTokens, presencePenalty, topP",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
