### ISSUE TITLE
请问token计算的问题

### ISSUE THREAD

**Issue by zzy-life** [Grt1228/chatgpt-java#140]
我使用gpt-3模型计算两个字token是2
![image](https://github.com/Grt1228/chatgpt-java/assets/68179477/8c48a80e-b741-445b-be9a-3d57f4254af4)
可是官网的分词器显示是5
![image](https://github.com/Grt1228/chatgpt-java/assets/68179477/acd4579d-09b4-4e7c-880e-db8ae822aa50)

**Comment by Grt1228** [comment]
官方这个实例是的是达芬奇-3模型。不是gpt-3.5.

**Comment by Grt1228** [comment]
@zzy-life

**Comment by zzy-life** [comment]
> 官方这个实例是达芬奇-3模型。不是gpt-3.5。

好的
