### ISSUE TITLE
maven报错

### ISSUE THREAD

**Issue by haogegenizhenbang** [Grt1228/chatgpt-java#142]
你好，我想请问一下我这个maven报错该怎么解决：问题如下：
无法解析 com.fasterxml.jackson.core:jackson-databind:pom:2.13.3 failed to transfer from http://maven.aliyun.com/nexus/content/groups/public/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of alimaven has elapsed or updates are forced. Original error: Could not transfer artifact com.fasterxml.jackson.core:jackson-databind:pom:2.13.3 from/to alimaven (http://maven.aliyun.com/nexus/content/groups/public/): transfer failed for http://maven.aliyun.com/nexus/content/groups/public/com/fasterxml/jackson/core/jackson-databind/2.13.3/jackson-databind-2.13.3.pom, status: 502 Bad Gateway
![image](https://github.com/Grt1228/chatgpt-java/assets/44430056/0392c067-f215-4a68-a7ec-5f2b028ebd19)

**Comment by Grt1228** [comment]
reload  maven。试试
