### ISSUE TITLE
DynamicKeyOpenAiAuthInterceptor遇到invalid key 不会自动容灾重试切换key嘛

### ISSUE THREAD

**Issue by 674345386** [Grt1228/chatgpt-java#150]
DynamicKeyOpenAiAuthInterceptor遇到invalid key 不会自动容灾重试切换key嘛

现在只是会remove invalid key,但是本次请求还是会异常

**Comment by livghit** [comment]
@Grt1228 This is true , we could implement a list with valid keys and if a key fails it should automaticly tale the next key . Doese this sound good ?

**Comment by Grt1228** [comment]
> 

目前是实现的移除失效的或者欠费的key。如果你要自动切换的。可以extends OpenAiAuthInterceptor自己重写写逻辑，创建Client的时候设置进去即可。（builder.authInterceptor）

**Comment by Grt1228** [comment]
> @Grt1228 This is true , we could implement a list with valid keys and if a key fails it should automaticly tale the next key . Doese this sound good ?

@livghit @674345386 


Currently, it is implemented to remove invalid or overdue keys. If you want to switch automatically. You can extend the OpenAiAuthInterceptor to rewrite the writing logic yourself, and set it when creating a client.
