### ISSUE TITLE
Get into wechat group

### ISSUE THREAD

**Issue by Fdr3iZzz** [Grt1228/chatgpt-java#156]
Hey, I saw you use Wechat to communicate and I'd like to join your group but as a foreigner I cannot create an account. I need someone already on wechat to scan my qr code. You can contact me here, over email, discord, signal, matrix or telegram.
Thank you very much in advance.

**Comment by Grt1228** [comment]
tell me your wechat id 


> Hey, I saw you use Wechat to communicate and I'd like to join your group but as a foreigner I cannot create an account. I need someone already on wechat to scan my qr code. You can contact me here, over email, discord, signal, matrix or telegram. Thank you very much in advance.

@Fdr3iZzz

**Comment by Fdr3iZzz** [comment]
Hey, I have to make an account and I need someone to scann this qr code so I am allowed in.
![2023-06-14 um 08 44 25](https://github.com/Grt1228/chatgpt-java/assets/37617308/e6304c1d-3e8a-494d-a8ec-58adc60a6949)
