### ISSUE TITLE
支持函数调用

### ISSUE THREAD

**Issue by 136William136** [Grt1228/chatgpt-java#159]
OpenAI的接口现在支持函数调用了，类似langchain, 可以接入吗？

**Comment by Grt1228** [comment]
开发中

**Comment by Grt1228** [comment]
> OpenAI的接口现在支持函数调用了，类似langchain, 可以接入吗？

支持种

**Comment by masaimu** [comment]
gogogo

**Comment by Grt1228** [comment]
@masaimu @136William136 
<dependency>
    <groupId>com.unfbx</groupId>
    <artifactId>chatgpt-java</artifactId>
    <version>1.0.14-beta1</version>
</dependency>

发布了个beta版本
支持最新的Gpt3.5-16k模型以及最新的0613模型
支持最新的Function calling功能。
示例参考：https://github.com/Grt1228/chatgpt-java/blob/1.0.14/src/test/java/com/unfbx/chatgpt/OpenAiClientFunctionTest.java
