### ISSUE TITLE
1.0.14有问题

### ISSUE THREAD

**Issue by zzy-life** [Grt1228/chatgpt-java#167]
![image](https://github.com/Grt1228/chatgpt-java/assets/68179477/ff714bff-aedf-4b5b-8ab0-3dc65f58c601)

**Comment by zzy-life** [comment]
应该是发包有问题，pom下不到，我在maven仓库下载jar替换1.0.13的本地仓库就可以用了

**Comment by Grt1228** [comment]
中央仓库有。明天发布release 1.0.14
