### ISSUE TITLE
v1/dashboard/billing/subscription接口报错

### ISSUE THREAD

**Issue by shican1234** [Grt1228/chatgpt-java#169]
看错误好像是加了一个字段返回格式化不出来了
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "primary" (class com.unfbx.chatgpt.entity.billing.Subscription), not marked as ignorable (19 known properties: "access_until", "tax_ids", "soft_limit", "hard_limit", "plan", "soft_limit_usd", "hard_limit_usd", "billing_address", "business_address", "delinquent", "billing_email", "canceled", "account_name", "system_hard_limit_usd", "object", "po_number", "system_hard_limit", "canceled_at", "has_payment_method"])
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 18, column: 18] (through reference chain: com.unfbx.chatgpt.entity.billing.Subscription["primary"])

**Comment by yqji** [comment]
+1

**Comment by Grt1228** [comment]
已修复 明天发布新版本

**Comment by Grt1228** [comment]
已修复
@yqji @shican1234 更新到1.0.14版本
