### ISSUE TITLE
ChatGPTTest 替换 apiKey 报错

### ISSUE THREAD

**Issue by java668** [Grt1228/chatgpt-java#17]
错误信息：
{
  "error": {
    "message": "Unrecognized request arguments supplied: bestOf, frequencyPenalty, maxTokens, presencePenalty, topP",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}

**Comment by Grt1228** [comment]
使用OpenAIClient方式调用。ChatGPTClient后期可能会废弃。
参考代码：
https://github.com/Grt1228/chatgpt-java/blob/main/src/test/java/com/unfbx/chatgpt/OpenAiClientTest.java

中的：completions，completionsV2，completionsV3这三种方式
@java668
