### ISSUE TITLE
Tokens计算问题

### ISSUE THREAD

**Issue by intblank** [Grt1228/chatgpt-java#174]
大佬，token计算方法变了，问题都按照GPT4的方法计算了，流式输出结果好像也改成了和普通结果相同的计算方法（所有content拼接起来计算）
![image](https://github.com/Grt1228/chatgpt-java/assets/75822497/672cafc1-1956-4f63-89e5-eb3e099b588e)

**Comment by intblank** [comment]
打扰了，最新版已经更新了

**Comment by Grt1228** [comment]
1.0.14 release 已经支持
