### ISSUE TITLE
SDK案列-JoyChat悦聊AI助手

### ISSUE THREAD

**Issue by didiEvans** [Grt1228/chatgpt-java#175]
*项目名称：
项目开源地址：暂未开源
*项目简介：基于chatgpt-java打造的Ai会话助手
*项目类型：氚云软件开发工作室
*使用到的SDK：chatgpt-java
二维码或访问地址：https://joychat.cceven.cc

**Comment by Grt1228** [comment]
@didiEvans 在issue：https://github.com/Grt1228/chatgpt-java/issues/87 添加
