### ISSUE TITLE
这个上下文是如何关联的

### ISSUE THREAD

**Issue by aaafsf** [Grt1228/chatgpt-java#176]
![微信图片_20230626191958](https://github.com/Grt1228/chatgpt-java/assets/29397705/8cf2c250-59f7-4735-9ac4-bf18e5cb1d89)
大佬，帮忙看看为什么问到第四个问题的时候，不回答了，直接把第一个问题的答案又发了一遍

**Comment by Grt1228** [comment]
你好 ，这个项目时demo的演示项目。可能存在不合理的地方需要自行修改。
联系上下文问答，从官方文档上可以知道是通过构建Message list 实现的。具体 的处理逻辑需要根据需求自行修改。
比如：通过参数控制是否关联上下文。
当需要重新开启一个话题是，可以通过构建新的会话实现（清除原来的message list），类似于chatspt官网的形式，增加会话窗口。

**Comment by Grt1228** [comment]
@aaafsf

**Comment by aaafsf** [comment]
可能是前一个问题还没答完，后一个问题又提出了，我先阻止下前一个问题流式输出完毕前提新问题
