### ISSUE TITLE
openAI的Moderation接口，Categories有更新，接口调用抛出异常

### ISSUE THREAD

**Issue by sjl1989** [Grt1228/chatgpt-java#178]
openAi的接口新增了新类型，https://platform.openai.com/docs/guides/moderation/overview

调用时返回异常：
java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "harassment" (class com.unfbx.chatgpt.entity.moderations.Categories), not marked as ignorable (7 known properties: "sexual/minors", "violence/graphic", "self-harm", "hate", "violence", "sexual", "hate/threatening"])
at [Source: okhttp3.ResponseBody$BomAwareReader@27b74cb4; line: 1, column: 162] (through reference chain: com.unfbx.chatgpt.entity.moderations.ModerationResponse["results"]->java.util.ArrayList[0]->com.unfbx.chatgpt.entity.moderations.Result["categories"]->com.unfbx.chatgpt.entity.moderations.Categories["harassment"])

**Comment by Grt1228** [comment]
@sjl1989 谢谢你分反馈。
- 关于报错：请更新值v1.0.14即可。
- 关于增加字段：下版本增加

> openAi的接口新增了新类型，https://platform.openai.com/docs/guides/moderation/overview
> 
> 调用时返回异常： java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "harassment" (class com.unfbx.chatgpt.entity.moderations.Categories), not marked as ignorable (7 known properties: "sexual/minors", "violence/graphic", "self-harm", "hate", "violence", "sexual", "hate/threatening"]) at [Source: okhttp3.ResponseBody$BomAwareReader@27b74cb4; line: 1, column: 162] (through reference chain: com.unfbx.chatgpt.entity.moderations.ModerationResponse["results"]->java.util.ArrayList[0]->com.unfbx.chatgpt.entity.moderations.Result["categories"]->com.unfbx.chatgpt.entity.moderations.Categories["harassment"])
