### ISSUE TITLE
如何解决接口返回的SocketTimeOutException问题，或者调大等待时间

### ISSUE THREAD

**Issue by ZHOURI** [Grt1228/chatgpt-java#18]

**Comment by Grt1228** [comment]
OpenAiClient 构造函数传入超时时间即可默认30秒，可以手动设置。
OpenAiClient openAiClient = new OpenAiClient("sk***************************",60,60,60);

**Comment by Grt1228** [comment]
@ZHOURI

**Comment by ZHOURI** [comment]
嗯嗯，谢谢，确实可以解决问题
