### ISSUE TITLE
问下一个问题，却还在回答上一个问题相关的内容

### ISSUE THREAD

**Issue by aragron** [Grt1228/chatgpt-java#187]
![image](https://github.com/Grt1228/chatgpt-java/assets/24290101/f2bdf5b0-ddeb-4299-aed2-c7911804ca4a)

**Comment by Grt1228** [comment]
这个项目只是一个demo。
你这种情况需要新创建会话窗口，实现会话之间的独立。（需要自行编程实现）

**Comment by Grt1228** [comment]
@aragron 或者在前端页面增加一个 清楚按钮。清楚之前的回答历史信息。
