### ISSUE TITLE
问一下，项目是不是有什么地方限制了并发数

### ISSUE THREAD

**Issue by hxyfj** [Grt1228/chatgpt-java#188]
WebSocket参考：OpenAIWebSocketEventSourceListener
参考以上项目 上线了，一开始没什么问题，最近发现连接数有7、8个以上的时候，响应就变得很慢，请问是有什么地方控制了并发数吗？

**Comment by lin-xiaosheng** [comment]
我也遇到了一样的问题，请问题主解决了吗
