### ISSUE TITLE
Functions类缺少无参构造器导致反序列化失败

### ISSUE THREAD

**Issue by FredGoo** [Grt1228/chatgpt-java#189]
@Data
@Builder
public class Functions implements Serializable {
    /**
     * 方法名称
     */
    private String name;
    /**
     * 方法描述
     */
    private String description;
    /**
     * 方法参数
     * 扩展参数可以继承Parameters自己实现，json格式的数据
     */
    private Parameters parameters;
}

这个类头上能不能加个@NoArgsConstructor注解

**Comment by FredGoo** [comment]
Parameters 也需要无参的构造器，麻烦处理下

**Comment by Grt1228** [comment]
@FredGoo 谢谢反馈

**Comment by FredGoo** [comment]
谢谢处理
