### ISSUE TITLE
为什么我用这个库，提问今天日期，返回的是2020年7月14日？

### ISSUE THREAD

**Issue by gG2se** [Grt1228/chatgpt-java#19]

**Comment by Grt1228** [comment]
![image](https://user-images.githubusercontent.com/27008803/220882106-3af8d122-8859-40f0-b62c-5bacae482011.png)
使用官方的实例方式返回也是这个。是挺奇怪的

**Comment by gG2se** [comment]
确实很奇怪，我用了github star最多的几个库返回都是这样，而且返回的结果都是很久之前的东西。
但是，我用python star最多的库，返回的却是正确的。奇怪的很

**Comment by gG2se** [comment]
不过我在python上用的不是API KEY，而且Access token

**Comment by Grt1228** [comment]
@gG2se Access token可能是使用的官方网页版的版本，类似爬虫的功能？？？
api keys调用的官方接口
