### ISSUE TITLE
请问如何在SSE流式输出完毕后获取完整的输出内容

### ISSUE THREAD

**Issue by wangpenghua** [Grt1228/chatgpt-java#191]
最近才接触这个SSE技术，我想在SSE流式输出完毕后获取完整的输出内容存到数据库，请问要怎么获取？

**Comment by 1654366772** [comment]
继承EventSourceListener类的时候，创建两个变量，一个string变量用于保存最新数据的，一个函数变量用于设置你的方法，在获得数据的时候用变量保存起来，在获取到[done]的时候掉用函数变量，并把最新的数据传递到函数变量里，比如：this.onComplate.accept(this.lastMessage); onComplate为函数变量，accept方法里放的是参数
最后在你的实现层，实例化你的listener类后，调用函数变量的set方法，把你的具体逻辑写进去就好了
实现代码你可以到隔壁同名的项目里看看，里面有具体的实现

**Comment by wangpenghua** [comment]
隔壁的同名项目我看了，我以为有其他优雅一点的方法！
感谢回复！
