### ISSUE TITLE
这个方法是不是不行了啊v1/dashboard/billing/usage

### ISSUE THREAD

**Issue by shican1234** [Grt1228/chatgpt-java#194]
[main] ERROR com.unfbx.chatgpt.interceptor.OpenAiResponseInterceptor - --------> 请求异常：{
  "error": {
    "message": "Your request to GET /v1/dashboard/billing/usage must be made with a session key (that is, it can only be made from the browser). You made it with the following key type: secret.",
    "type": "server_error",
    "param": null,
    "code": null
  }
}

**Comment by aaronyy9** [comment]
需要：SESSION_ID和ORG_ID  比如： -H "Authorization: Bearer $SESSION_ID"   -H 'Openai-Organization: $ORG_ID'

**Comment by Grt1228** [comment]
@shican1234 谢谢反馈。这个接口可能被官方禁用了。晚点再看下是否有其他途径
