### ISSUE TITLE
Fine-tune接口参数报错

### ISSUE THREAD

**Issue by lokbun** [Grt1228/chatgpt-java#205]
Fine-tune的使用遇到两个问题：
1:OpenAI的fine-tune接口地址变化
接口内的地址是：
`Post https://api.openai.com/v1/fine-tunes`
新地址是：
`Post https://api.openai.com/v1/fine_tuning/jobs`
目前通过nginx转发，暂时可以解决地址的问题。

2:最新的fine-tune接口参数已经调整了，现在提示参数无效。

版本是1.0.15

**Comment by fitz-97** [comment]
+1

**Comment by Grt1228** [comment]
@fitz-97 @lokbun 升级1.1.2+版本
