### ISSUE TITLE
感觉返回时间有点过长

### ISSUE THREAD

**Issue by luoyashuo** [Grt1228/chatgpt-java#21]
我用单独发送http请求的方式，大概3s内就可以收到返回，但是相同的内容调用您的包，发现返回时间大概要10s甚至更久，不知道这个时长是产生在了哪里？

**Comment by alon-sys** [comment]
我也是碰到这个问题

**Comment by alon-sys** [comment]
其实是model的问题，davinci是最慢的

**Comment by Grt1228** [comment]
查了下资料，说是设置ipv4可以缓解你试试增加启动参数：-Djava.net.preferIPv4Stack=true

你还可以测试下同一个OpenAiClient  连续发送请求，第二次第三次好像就快了。

**Comment by Grt1228** [comment]
查了下资料，说是设置ipv4可以缓解你试试增加启动参数：-Djava.net.preferIPv4Stack=true

你还可以测试下同一个OpenAiClient  连续发送请求，第二次第三次好像就快了。

**Comment by Grt1228** [comment]
1.0.2版本以支持流式输出可以试试
