### ISSUE TITLE
使用流式客户端，api返回数据乱码

### ISSUE THREAD

**Issue by Conanxy** [Grt1228/chatgpt-java#236]
OpenAI  sse连接异常data：data: {"id":"chatcmpl-8Rdsasddsaddpo06zCs","object":"chat.completion.chunk","created":1701599827,"model":"gpt-3.5-turbo-0613","system_fingerprint":null,"choices":[{"index":0,"delta":{"role":"assistant","content":""},"finish_reason":null}]}

object":"chat.completion.chunk","created":1701599827,"model":"gpt-3.5-turbo-0613","system_fingerprint":null,"choices":[{"index":0,"delta":{"content":"ä½ "},"finish_reason":null}]}

data: {"id":"chatcmpl-8Re8RfM7Undj3UdUbLspsdpo06zCs","object":"chat.completion.chunk","created":1701599827,"model":"gpt-3.5-turbo-0613","system_fingerprint":null,"choices":[{"index":0,"delta":{"content":"å¥½"},"finish_reason":null}]}

data: {"id":"chatcmpl-8Re8RfM7Undj3UdUbLspsdpo06zCs","object":"chat.completion.chunk","created":1701599827,"model":"gpt-3.5-turbo-0613","system_fingerprint":null,"choices":[{"index":0,"delta":{"content":"ï¼"},"finish_reason":null}]}

**Comment by Grt1228** [comment]
这个感觉是openai的问题  你再试试 添加点语言说明试试

比如：请使用中文回复
