### ISSUE TITLE
ChatGPTTest运行报错

### ISSUE THREAD

**Issue by alon-sys** [Grt1228/chatgpt-java#25]
[main] INFO com.unfbx.chatgpt.ChatGPTClient - 调用ChatGPT请求返回值：{
  "error": {
    "message": "Unrecognized request arguments supplied: bestOf, frequencyPenalty, maxTokens, presencePenalty, topP",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}

**Comment by Grt1228** [comment]
1.0.1以上版本使用OpenAiClient
实例参考源码的：com.unfbx.chatgpt.OpenAiClientTest
