### ISSUE TITLE
ChatCompletionResponse 里面 choices 集合中，根据OpenAi最新接口返回应该为：deltad对象而不是message

### ISSUE THREAD

**Issue by Bobby0403** [Grt1228/chatgpt-java#31]
{
    "id":"chatcmpl-6qEA9KPno54zzFZCJLfWfDofxoDbX",
    "object":"chat.completion.chunk",
    "created":1677905517,
    "model":"gpt-3.5-turbo-0301",
    "choices":[
        {
            "delta":{
                "role":"assistant"
            },
            "index":0,
            "finish_reason":null
        }
    ]
}
增加注解：@JsonProperty("delta")
![image](https://user-images.githubusercontent.com/126938316/222877152-2d33a972-c5f8-4995-bae7-6c5da66a160e.png)

**Comment by Grt1228** [comment]
测试了下是stream模式下返回值改为了delta。
已更新支持，升级到1.0.4即可
<dependency>
    <groupId>com.unfbx</groupId>
    <artifactId>chatgpt-java</artifactId>
    <version>1.0.4</version>
</dependency>
