### ISSUE TITLE
sse方式支持同一KEY，多个人同时提问吗？

### ISSUE THREAD

**Issue by jiushaba** [Grt1228/chatgpt-java#33]
sse方式支持同一KEY，多个人同时提问吗？

**Comment by Grt1228** [comment]
https://github.com/Grt1228/chatgpt-steam-output

参考下这个项目

**Comment by alon-sys** [comment]
> 我就是按这个写的，但是用同一KEY，多个人同时提问，返回会出问题

先看文档，总不能一个用户一个KEY吧😂

**Comment by alon-sys** [comment]
> https://github.com/Grt1228/chatgpt-steam-output
> 
> 参考下这个项目

建议Message.java改个名称，很容易跟别的冲突

**Comment by jiushaba** [comment]
> > https://github.com/Grt1228/chatgpt-steam-output
> > 参考下这个项目
> 
> 建议Message.java改个名称，很容易跟别的冲突

有联系方式吗？付费请教一下

**Comment by PlexPt** [comment]
官方限流，每分钟20000token
