### ISSUE TITLE
流式输出能集成支持一下websocket吗，小程序貌似不支持sse

### ISSUE THREAD

**Issue by soulForLove** [Grt1228/chatgpt-java#36]

**Comment by Grt1228** [comment]
这个还需要再看看，后续版本可以考虑

**Comment by shawking3156** [comment]
这个自己动手改一下就行了，什么都衣来伸手饭来张口的别做什么开发者了

**Comment by Grt1228** [comment]
参考下这个项目：https://github.com/Grt1228/chatgpt-steam-output
接收到信息后通过socket发送到前端应该就可以了。
我还没来得及实现，这两天实现下试试。你也可以自己试试
@soulForLove
