### ISSUE TITLE
1.0.4版本貌似会有okhttp包冲突问题

### ISSUE THREAD

**Issue by DrBit666** [Grt1228/chatgpt-java#40]
引入okHttp 3.8.1版本中的HttpUrl.get方法参数为get(URL url)，但是在Retrofit中调用HttpUrl.get(String url)，会报NoSuchMethodError: okhttp3.HttpUrl.get(Ljava/lang/String;)Lokhttp3/HttpUrl;
手动引入okHttp3.12.0之后，不再报错

但是使用流展示的实例时，又会遇到新的版本冲突问题，具体原因没有找到，貌似是因为okHttp-see这个包的版本有问题

**Comment by nayu-dayo** [comment]
引入okHttp3.12.0之后报一个新的错误NoSuchMethodError: okhttp3.RequestBody.isDuplex()Z，想请教一下是什么原因
