### ISSUE TITLE
你们难道没人报证书的错嘛？？

### ISSUE THREAD

**Issue by onega1** [Grt1228/chatgpt-java#46]
![图片](https://user-images.githubusercontent.com/55702118/223524502-20d36afb-5774-4e15-9512-2cdffe41d777.png)
你们是咋绕过https的证书认证的。。。

**Comment by Grt1228** [comment]
jdk是1.8么？

**Comment by 202252197** [comment]
> JDK是1.8么？

我的是jdk11也不行

**Comment by 202252197** [comment]
> ![图片](https://user-images.githubusercontent.com/55702118/223524502-20d36afb-5774-4e15-9512-2cdffe41d777.png)你们是咋绕过https的证书认证的。。。

我也是这个错误，我把证书添加近jdk仍然报错，把jdk升级到11,19还是不行

**Comment by ly147369** [comment]
同问

**Comment by jiangshiying09k** [comment]
![image](https://user-images.githubusercontent.com/89025082/223930994-daad3d99-0116-4fa9-befa-bd18581f2ee4.png)
我的1.8

**Comment by OutsiderVictor** [comment]
可以本地导入证书，或者该代码，忽略证书验证

**Comment by Grt1228** [comment]
升级jdk版本 可以解决这个问题，之前有几位朋友遇到过。
我开发jdk版本  1.8.0_144
