### ISSUE TITLE
如何训练自己的模型? 例如提供部分数据训练GPT, 让GPT学习, 变为一个较为个性化的模型

### ISSUE THREAD

**Issue by ly147369** [Grt1228/chatgpt-java#47]

**Comment by Grt1228** [comment]
参考官方的Fine-tune相关文档
接口的话就使用项目中的FineTune相关api

**Comment by tiger822** [comment]
> 参考官方的Fine-tune相关文档 接口的话，我这个项目已经集成了FineTune相关api @ly147369

有test例子吗?
