### ISSUE TITLE
在使用ChatGPT 3.5 类模型时遇到的报错

### ISSUE THREAD

**Issue by PengLx** [Grt1228/chatgpt-java#48]
`try {

            val client = buildClient()
            val eventSourceListener = ChatEventSourceListener(chat, Model.CHATGPT_3_5_TURBO)
            val message = Message.builder().role(Message.Role.USER).content(text).build()
            val chatCompletion = ChatCompletion.builder().messages(listOf(message)).build()
            client!!.streamChatCompletion(chatCompletion, eventSourceListener)
            val countDownLatch = CountDownLatch(1)

            try {
                countDownLatch.await()
            } catch (e: InterruptedException) {
                e.printStackTrace()
            }
        } catch (e: Exception) {
            chat.msgs.add(Msg(chat.friend, mutableStateOf(e.stackTraceToString()), dateFormat))
        }`

错误显示

OpenAI SSE链接异常 data: {
	"error": {
		"message": "Invalid URL (POST /v1/chat/completions)",
		"type": "invalid_request_error",
		"param": null,
		"code": null
	}
} 异常 null

**Comment by PengLx** [comment]
测试使用达芬奇模型无此问题

**Comment by Grt1228** [comment]
应该是你的参数入参有问题。建议断点看下。
这个报错是官方返回的

**Comment by PengLx** [comment]
> 

`            val client = buildClient()
            val eventSourceListener = ChatEventSourceListener(chat, Model.CHATGPT_3_5_TURBO)
            val message = Message.builder().role(Message.Role.USER).content("你好啊我的伙伴！").build()
            val chatCompletion = ChatCompletion.builder().messages(listOf(message)).build()
            client!!.streamChatCompletion(chatCompletion, eventSourceListener)
            val countDownLatch = CountDownLatch(1)

            try {
                countDownLatch.await()
            } catch (e: InterruptedException) {
                e.printStackTrace()
            }`

即使使用样例也是发出同样的返回
OpenAiStreamClientTest.java

**Comment by Grt1228** [comment]
@PengLx 可以进去具体看下你的问题
