### ISSUE TITLE
OpenAI  sse连接异常 大家有人遇到这个错误吗？怎么解决的呢

### ISSUE THREAD

**Issue by CoderAndTester** [Grt1228/chatgpt-java#49]
![image](https://user-images.githubusercontent.com/127287549/223643468-e7e15161-def2-468a-a192-4e5a8de99d5b.png)

**Comment by Grt1228** [comment]
需要梯子才能访问了。没梯子可以参考https://github.com/noobnooc/noobnooc/discussions/9

**Comment by WarriorFromLongAgo** [comment]
我本地在使用 clash for windows ，链接的是新加坡节点，也尝试过美国节点。

但是仍然报错，请问是clash代理的问题么。
