### ISSUE TITLE
不加代理就失败

### ISSUE THREAD

**Issue by sebord** [Grt1228/chatgpt-java#50]
![image](https://user-images.githubusercontent.com/104607562/223671978-2189cf0d-0da1-460f-be30-ea1a168b78a2.png)
![image](https://user-images.githubusercontent.com/104607562/223672062-415a008c-2d22-4be1-a7ae-e86459ea37ff.png)

**Comment by Grt1228** [comment]
现在直接访问openai的接口是需要梯子的。
建议参考：https://github.com/noobnooc/noobnooc/discussions/9
自己做一下代理 ，也很简单
