### ISSUE TITLE
请求超时问题

### ISSUE THREAD

**Issue by YDXyydsyyds** [Grt1228/chatgpt-java#51]
为什么用了梯子能通过浏览器访问chatgpt接口，然而使用hutools发送请求超时（访问国内的网站能够响应得到数据）
![800_LI (2)](https://user-images.githubusercontent.com/104897103/223739634-33324713-845d-4042-9f4b-bda1b451cda4.jpg)
![userAvater](https://user-images.githubusercontent.com/104897103/223739687-2acf35be-8b2f-4fee-95ab-9407f0e2e823.jpg)

**Comment by Grt1228** [comment]
没代理你程序里的请求。
需要手动设置Httprequest的代理，或者设置idea的代理

**Comment by YDXyydsyyds** [comment]
谢谢，原来用了梯子还得设置代理

**Comment by TremorLY** [comment]
问题解决了吗，我可能需要问下你

**Comment by TremorLY** [comment]
我设置了 但是还是不行
加vx 聊下啊

**Comment by TremorLY** [comment]
Proxy proxy = new Proxy(Proxy.Type.SOCKS, new InetSocketAddress("127.0.0.1", 10808));
        HttpLoggingInterceptor httpLoggingInterceptor = new HttpLoggingInterceptor(new OpenAILogger());

**Comment by YDXyydsyyds** [comment]
协议类型是http，端口号是10809，你写的是10808

**Comment by TremorLY** [comment]
![e33100d29fca1aed19f212dba8a6115](https://user-images.githubusercontent.com/127409263/224036590-66a36df9-8eed-4b1d-a83a-49dc4e87385d.png)

**Comment by YDXyydsyyds** [comment]
跟你的一模一样，你用10809试试，我用10808也报错

**Comment by TremorLY** [comment]
![825af3ed7041884b6abec3a543ecbab](https://user-images.githubusercontent.com/127409263/224046122-a3653ca9-2f91-4608-9b38-11f92539b5cc.png)

**Comment by TremorLY** [comment]
太难了啊

**Comment by YDXyydsyyds** [comment]
你别改这个啊，兄弟，服务器上的10808别改，改了就会报错，这两个端口号作用是不同的，改了就会占用同一个

**Comment by a1265137718** [comment]
> 我设置了 但是还是不行 加vx 聊下啊

香港服务器是不行的

**Comment by a1265137718** [comment]
Proxy proxy = new Proxy(Proxy.Type.SOCKS, new InetSocketAddress("127.0.0.1", 10808)); 
OpenAiClient.Builder builder = OpenAiClient.builder();
builder.proxy(PROXY);

**Comment by gclhaha** [comment]
> 问题解决了，将代理设置为127.0.0.1 端口号为10809（本地运行了一个代理服务器，端口号为这个，也就是你的梯子）就可以访问外网

兄弟，key记得在官网上删了重新生成一个，别被乱用了

**Comment by gclhaha** [comment]
> 问题解决了，将代理设置为127.0.0.1 端口号为10809（本地运行了一个代理服务器，端口号为这个，也就是你的梯子）就可以访问外网

终于，换成127001 p能访问了
