### ISSUE TITLE
催更websocket连接

### ISSUE THREAD

**Issue by godJBJ** [Grt1228/chatgpt-java#52]
您好，请问websocket连接在实现了嘛~小程序实现不了sse，催催~~~~~

**Comment by m9d2** [comment]
可以试试这个https://github.com/m9d2/chatgpt😂

**Comment by godJBJ** [comment]
openAI开始封号了，有解决措施嘛😂

**Comment by Grt1228** [comment]
> 

参考下这个项目：https://github.com/Grt1228/chatgpt-steam-output
接收到信息后通过socket发送到前端应该就可以了。
我还没来得及实现，这两天实现下试试。你也可以自己试试

**Comment by m9d2** [comment]
> 
websocket应该得自己实现吧，我们也是作为sse客户端接收的openai服务器端的数据，我的理解是，在自己的项目中再实现个websocket服务端，小程序作为客户端接收数据

**Comment by Grt1228** [comment]
> > 您好，请问websocket连接在实现了嘛~小程序实现不了sse，催催~~~~~
> 
> websocket应该得自己实现吧，我们也是作为sse客户端接收的openai服务器端的数据，我的理解是，在自己的项目中再实现个websocket服务端，小程序作为客户端接收数据

正解，需要自己动手自定义下
