### ISSUE TITLE
请问如何实现才能实现上下文有联系的AI对话?

### ISSUE THREAD

**Issue by tiger822** [Grt1228/chatgpt-java#56]
如题，比如我连续提问，后面的答非所问：
`
@Test
  public void chat() {
    //聊天模型：gpt-3.5
    Message message = Message.builder().role(Message.Role.USER).content("现在的光刻机最先进的型号是什么！").build();
    ChatCompletion chatCompletion = ChatCompletion.builder().messages(Arrays.asList(message)).build();
    ChatCompletionResponse chatCompletionResponse = v2.chatCompletion(chatCompletion);
    chatCompletionResponse.getChoices().forEach(e -> {
      System.out.println(e.getMessage());
    });

    CompletionResponse completions = v2.completions("那么中国企业在用的是什么型号?");
    for (Choice choice : completions.getChoices()) {
      System.out.println(choice.getText());
    }
    completions = v2.completions("是哪家企业?");
    for (Choice choice : completions.getChoices()) {
      System.out.println(choice.getText());
    }
  }

`

**Comment by tiger822** [comment]
另外，比如我有多个api-key,开多个OpenAiClient，那怎么才能实现 实例1的上下文，实例2能接得上？？

**Comment by Grt1228** [comment]
参考我的实现示例，可以直接拉下来运行
https://github.com/Grt1228/chatgpt-steam-output

**Comment by tiger822** [comment]
> 参考我的实现示例，可以直接拉下来运行 https://github.com/Grt1228/chatgpt-steam-output

谢谢!
