### ISSUE TITLE
sse 连接异常

### ISSUE THREAD

**Issue by a616567126** [Grt1228/chatgpt-java#58]
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/43660702/224521821-6a20c749-735d-4487-b698-2c9c3fb06c0f.png">

**Comment by Grt1228** [comment]
做了代理么？

**Comment by a616567126** [comment]
> 做了代理什么？

我本地用clash 代理无效放到香港的服务器上就没这个问题了

**Comment by HuntLee770090834** [comment]
> > 做了代理什么？
> 
> 我本地用clash 代理无效放到香港的服务器上就没这个问题了

   一定要海外服务器么？ 我本地挂的梯子 现在一直报这个错😭😭

**Comment by Grt1228** [comment]
> > > 做了代理什么？
> > 
> > 
> > 我本地用clash 代理无效放到香港的服务器上就没这个问题了
> 
> 一定要海外服务器么？ 我本地挂的梯子 现在一直报这个错😭😭

本地代码需要做一下代理，build时候构建proxy对象
