### ISSUE TITLE
图片生成或图片编辑能不能实现上下文功能？

### ISSUE THREAD

**Issue by tiger822** [Grt1228/chatgpt-java#59]
感觉参数里面少了context参数？

**Comment by Grt1228** [comment]
目前最新的官方文档没有这个参数
![image](https://user-images.githubusercontent.com/27008803/224589253-d4587f54-b05d-44b8-996e-f92e81db320b.png)
![image](https://user-images.githubusercontent.com/27008803/224589280-ed5c8a4b-dbd2-4f01-81d6-d792610b5e0d.png)
