### ISSUE TITLE
能否添加GPT-3-Encoder？ 方便精确计算tokens

### ISSUE THREAD

**Issue by reinershir** [Grt1228/chatgpt-java#66]
目前github上还没有java版的GPT-3-Encoder

**Comment by Grt1228** [comment]
近期在看这块

**Comment by shuibuxing0023** [comment]
请问可以发下GPT-3-Encoder一些相关的资料吗

**Comment by shuibuxing0023** [comment]
> 近期在看这块

请问可以发下GPT-3-Encoder一些相关的资料吗

**Comment by Grt1228** [comment]
> > 近期在看这块
> 
> 请问可以发下GPT-3-Encoder一些相关的资料吗

https://github.com/openai/tiktoken

**Comment by Grt1228** [comment]
以支持 升级1.0.10
@reinershir @shuibuxing0023
