### ISSUE TITLE
Image中的ResponseFormat中的B64_JSON定义错了

### ISSUE THREAD

**Issue by seven-cm** [Grt1228/chatgpt-java#76]
```
public enum ResponseFormat implements Serializable {
    URL("url"),
    B64_JSON("urlb64_json"),
    ;

    private String name;
}
```

[接口文档](https://platform.openai.com/docs/api-reference/images/create)是：
The format in which the generated images are returned. Must be one of url or b64_json.

**Comment by Grt1228** [comment]
已修复更新1.0.7
