### ISSUE TITLE
反序列化报错

### ISSUE THREAD

**Issue by CCc3120** [Grt1228/chatgpt-java#79]
对象转成json传输后反序列化报错

![image](https://user-images.githubusercontent.com/45281857/226899659-250539a0-01cf-406c-816f-50c057a75a55.png)
 @Test
    public void testJson() throws JsonProcessingException {
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper
                .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
                .configure(SerializationFeature.INDENT_OUTPUT, true)
                .setSerializationInclusion(JsonInclude.Include.NON_NULL)
                .setTimeZone(TimeZone.getTimeZone("GMT+8"))
                .setLocale(Locale.CHINA);

        Completion completion = Completion.builder().prompt("你好啊").build();

        String jsonStr = objectMapper.writeValueAsString(completion);

        Completion completion1 = objectMapper.readValue(jsonStr, Completion.class);

    }

**Comment by 1018987534** [comment]
什么时候可以支持GPT4，目前1.0.6的model还是没有4,.0

**Comment by Grt1228** [comment]
> 什么时候可以支持GPT4，目前1.0.6的model还是没有4,.0

gpt4目前官方没有开放api。
如果你已经加入了官方的api使用用户列表，那么现在的1.0.6已经支持Gpt-4，只需要在构建Completion或者Completion的时候自定义模型即可
Completion completion = Completion.builder().prompt("你好啊").model("传入gpt4模型").build();
模型参考下面的Model：
https://github.com/Grt1228/chatgpt-java/blob/main/src/main/java/com/unfbx/chatgpt/entity/chat/ChatCompletion.java/

**Comment by 1018987534** [comment]
> > 什么时候可以支持GPT4，目前1.0.6的model还是没有4,.0
> 
> gpt4目前官方没有开放api。 如果你已经加入了官方的api使用用户列表，那么现在的1.0.6已经支持Gpt-4，只需要在构建Completion或者Completion的时候自定义模型即可 Completion completion = Completion.builder().prompt("你好啊").model("传入gpt4模型").build(); 模型参考下面的Model： https://github.com/Grt1228/chatgpt-java/blob/main/src/main/java/com/unfbx/chatgpt/entity/chat/ChatCompletion.java/

通过maven引用的还是只有GPT3.5两个模型，是不是没有发布到中央仓库

**Comment by Grt1228** [comment]
> > > 什么时候可以支持GPT4，目前1.0.6的model还是没有4,.0
> > 
> > 
> > gpt4目前官方没有开放api。 如果你已经加入了官方的api使用用户列表，那么现在的1.0.6已经支持Gpt-4，只需要在构建Completion或者Completion的时候自定义模型即可 Completion completion = Completion.builder().prompt("你好啊").model("传入gpt4模型").build(); 模型参考下面的Model： https://github.com/Grt1228/chatgpt-java/blob/main/src/main/java/com/unfbx/chatgpt/entity/chat/ChatCompletion.java/
> 
> 通过maven引用的还是只有GPT3.5两个模型，是不是没有发布到中央仓库

下个版本1.0.7会增加枚举值

**Comment by Grt1228** [comment]
已修复更新：1.0.7
