### ISSUE TITLE
这个怎么实现连续对话

### ISSUE THREAD

**Issue by sixawnstar** [Grt1228/chatgpt-java#8]
当前未找到在什么地方添加连续对话选项

**Comment by Grt1228** [comment]
看官网的介绍好像是没有的。也可能我没看到

**Comment by coder-ldh** [comment]
> 看官网的介绍好像是没有的。也可能我没看到

好像是把上一个对话返回的id传进去，我看有人这样操作的

**Comment by 807592732** [comment]
这样不太实用把。如果字数过多呢？

**Comment by Toifyx** [comment]
目前官方支持 gpt-3.5-turbo 模型 对话了

**Comment by a1667834841** [comment]
可以使用 chat啦
[Chat completions](https://platform.openai.com/docs/guides/chat/chat-completions-beta)

**Comment by Grt1228** [comment]
@Toifyx @a1667834841 @807592732    1.0.3版本 已经支持 gpt-3.5-turbo 模型 对话了。可以更新版本试试

**Comment by Peins** [comment]
就算是gpt-3.5-turbo 模型，还是得把前文消息传入，才能实现上下文，费钱，还限制字数了

**Comment by Peins** [comment]
> 那如果聊天回合多了之后,传输的数据量岂不是一直会阶梯增长?

会增长，但是有token限制，最多传多少吧

**Comment by wr345861927** [comment]
已经试了,触发了最大字数限制了
This model's maximum context length is 4097 tokens. However, you requested 4891 tokens (2843 in the messages, 2048 in the completion). Please reduce the length of the messages or completion.

**Comment by qujinqiang** [comment]
所以，解决方案是什么？

**Comment by atl1028** [comment]
session_id

**Comment by SnowyLchen** [comment]
> session_id

请问下如何使用sessionId实现

**Comment by XuanRanDev** [comment]
> session_id

session_id如何实现呢？有无demo

**Comment by Azrael-CP** [comment]
session_id怎么实现的呀，求告知

**Comment by littlesky007** [comment]
根据token，截取掉前面的对话
