### ISSUE TITLE
看日志好像是所有请求返回之后，event事件才开始触发

### ISSUE THREAD

**Issue by CaptainRuby** [Grt1228/chatgpt-java#93]
如果问一个比较长回复的问题，会有长时间的等待，直到http流输出回答完毕，才会有event事件的回调。这个设计感觉不符合流式响应。

**Comment by asdzheng** [comment]
@CaptainRuby 我用1.0.5版本并没有这个问题，但是用最新版本的1.0.8就有，你这个问题解决了么？

**Comment by CaptainRuby** [comment]
@asdzheng 我用WebClient解决，没有用okhttp

**Comment by Grt1228** [comment]
```
        HttpLoggingInterceptor httpLoggingInterceptor = new HttpLoggingInterceptor(new OpenAILogger());
        //！！！！千万别再生产或者测试环境打开BODY级别日志！！！！
        //！！！生产或者测试环境建议设置为这三种级别：NONE,BASIC,HEADERS,！！！
        httpLoggingInterceptor.setLevel(HttpLoggingInterceptor.Level.HEADERS);
```
        
        @CaptainRuby @asdzheng 找到问题了。看下上面的代码

**Comment by CaptainRuby** [comment]
@Grt1228 原理是啥，会阻塞线程吗

**Comment by Dkaishu** [comment]
OKhttp HttpLoggingInterceptor 实现机制问题吧，既然是Level.BODY，理应全部拿到后才给下一个interceptor。我理解的是，Level.BODY 和 SSE 是两个冲突的需求吧
这里有一些讨论：
https://github.com/square/okhttp/issues/4298
https://github.com/launchdarkly/okhttp-eventsource/issues/57
