### ISSUE TITLE
请问使用stream流式请求聊天接口后，如何获取到对应的usage中的各种tokens信息

### ISSUE THREAD

**Issue by liuyu-struggle** [Grt1228/chatgpt-java#95]
请问使用stream流式请求聊天接口后，如何获取到对应的usage中的各种tokens信息，
目前从接口返回看，非stream请求可以拿到response中的usage中的各种tokens信息，但是stream流式信息中的response中不会有usage信息

**Comment by Grt1228** [comment]
官方没有提供支持，暂时无解

**Comment by LuaIJ** [comment]
@Grt1228 ， 已经可以了，请求实体携带参数 "stream_options": {
	        "include_usage": true
	     }   即可，  但目前最新这个版本的请求实体没有包含这个属性，请更新版本，谢谢

**Comment by LuaIJ** [comment]
@liuyu-struggle 你处理好了吗
